### ISSUE TITLE
Importing .obj into indoor map ignores UV coordinates

### ISSUE THREAD

**Issue by kalimag** [GrayFace/MMExtension#1]
The import process does not save UV coordinates for newly imported facets on indoor maps. All `BitmapU`/`BitmapV` values are set to 0.

To reproduce

1. Open indoor internal map
1. Export
2. New
3. Import Objects or Import Rooms for the previously exported file

For example, MM8's d06 [before](https://user-images.githubusercontent.com/14197345/146432031-974f87ba-6273-4a7d-81c4-9ec9dd15f291.png) and [after](https://user-images.githubusercontent.com/14197345/146432215-ff09b8b8-17e5-44e7-8947-dd149aee8c38.png).

This affects at least MM7 and MM8. I have not tested MM6.

UVs are correctly saved when importing the .obj into outdoor maps, or when re-importing the .obj into the original map which already has UV data for the faces.

This problem does not occur on very old versions of the editor, as far as I can tell it happens since commit 068d51214f3de3f86a2931861fda1334ca986243. Forcing `a.HasData` to `true` seems to "solve" the problem, but I suspect that this is more of a workaround and not the correct fix?

**Comment by GrayFace** [comment]
Should be fixed now: https://github.com/GrayFace/MMExtension/commit/6784f477ce9a8594e9f6495b82208041ad39f308

**Comment by kalimag** [comment]
Works fine now, thank you.
