### ISSUE TITLE
Newest MMEditor: faulty doors processing

### ISSUE THREAD

**Issue by Rod-L** [GrayFace/MMExtension#10]
Upon openning indoor maps with newest editor, doors take wrong position and move into wrong direction on pressing "Door State" button. Compiling map causes this error to present in the game (means, just openning and compiling map without changes will break it anyway).
Error present in clean installation of MM8 + mmextension and mmeditor.
Abandoned temple looks like this: https://imgbb.com/VSD8vbv

**Comment by Rod-L** [comment]
Commenting out "ClearMovedByDoor()" function call in "Editor Read Data.lua" fixes the issue. It is minimal blind change, I don't have complete understanding of Editor routines.

**Comment by GrayFace** [comment]
I think it was there for editing convenience with new way of doing doors, which I've now changed as well. Thx for the report and fix.
