### ISSUE TITLE
Indoor UV coordinates are truncated instead of rounded

### ISSUE THREAD

**Issue by kalimag** [GrayFace/MMExtension#2]
UV coordinates are calculated and displayed as floating point values in the editor, but internally truncated to integers. With floating point imprecision and the Y/Z axis rotation during import it's fairly common to end up with coordinates like `127.999994` truncated to `127`, causing misaligned textures.

![image](https://user-images.githubusercontent.com/14197345/151387524-ea35ab35-466a-47a8-a73a-ffbd08e32008.png)

Outdoor maps don't have this problem, the UVs are rounded to the closest integer here:

https://github.com/GrayFace/MMExtension/blob/325d0643aa389db0f678fc82daf7063c443a0a28/Scripts/Global/Editor%20Data.lua#L440-L448

[Sample .obj that demonstrates the issue (using MM8 textures)](https://github.com/GrayFace/MMExtension/files/7951606/uvrounding.zip)

**Comment by GrayFace** [comment]
Fixed
