### ISSUE TITLE
Editor sometimes saves incorrect door UVs

### ISSUE THREAD

**Issue by kalimag** [GrayFace/MMExtension#3]
For doors with a `MoveLength`  which is not a multiple of the texture size (I think), the texture will appear offset when viewed in-game.

The UVs are correct in the editor, but are incorrect when loading the compiled map outside the editor. Loading the compiled map in the editor (via Internal Map) will once again calculate the UVs correctly.

The `Door.FacetStartU`/`Door.FacetStartV` are different when read in the editor and outside the editor, but I was unable to find out where this discrepancy comes from.

#### Reproduction steps:
1. Open MM8's `d45.dlv` in the editor
2. Compile map without making any changes
3. Insert into a LOD and restart game
4. Load map without the editor (`evt.MoveToMap{Name="d45.blv"}`)
5. Textures on the doors will be offset

#### Before:
![image](https://user-images.githubusercontent.com/14197345/151420316-80a10d76-a311-4651-a463-32bfd284a8e8.png) 
![image](https://user-images.githubusercontent.com/14197345/151420473-1b1f2fd4-5a19-4b92-973a-1f56a86f5ec2.png)

#### After:
![image](https://user-images.githubusercontent.com/14197345/151420961-1574b988-9a85-471a-90b4-53235efb3443.png)

**Comment by GrayFace** [comment]
Fixed
