### ISSUE TITLE
Setting a hireling name in MM6 does not stick.

### ISSUE THREAD

**Issue by RobertZenz** [GrayFace/MMExtension#6]
I wanted to [restore my hirelings after doing the temple quest in MM6](https://www.reddit.com/r/MightAndMagic/comments/unho3u/mm6_keep_hirelings_after_the_restoration_of_the/) and came up with a simple script to do that. However, setting the name of the hireling does not stick.

Steps to reproduce (MM6 with MMExt 2.2):

 1. Hire a hireling, any will do.
 2. Change the name with `Party.HiredNPC[1].Name = "Test"`.
 3. The new name is being displayed correctly.
 4. Save the game.
 5. Load that save.
 6. The name of the hireling has reverted to the original one.

The save file itself does also only contain the original name of the hireling.

Did I miss something on how I need to set the name of a hireling?

**Comment by GrayFace** [comment]
Now you can do it with `Party.HiredNPCName[1] = "Test"`

**Comment by RobertZenz** [comment]
Thank you.
