### ISSUE TITLE
MMExtension compatibility

### ISSUE THREAD

**Issue by Rod-L** [GrayFace/MMExtension#9]
Hello.
I'm updating MMMerge to current version of MMExtension, and I got into these troubles, worth to mention:

1. mem arrays do not accept boolean values anymore. For example 'mem.u4[ptr] = true' will give error now (unlike in previous MMExt version, where bool was correctly casted to 1 or 0). I can avoid assigning booleans, but it is troubling with evt functions, for example: 'evt.Set{const.VarNum.Poison1, true}', feels like correct code, but will give error as well, because 'true' is not converted to number underneath.
2. lua51.dll in the ExeMods folder sometimes crahses the game after call to RtlUnwind inside it. I could not reproduce the error in clean installation of MM8 + MMPatch + MMExtension, and it does not happen too often in the Merge, but still I did not have play session, where it would not happen at least once. After i recompiled this dll using vs2019 with it's bundled msvc_x86, error has gone (I've taken source from OpenResty repository and added lj_get_char_bits exported symbol accordingly).

**Comment by Rod-L** [comment]
Also encountered crash given by "GenerateItem" and "ItemGenerated" events, if at least one handler attached to any of those. 
Example:
```
function events.GenerateItem(t)
end
function events.ItemGenerated(t)
end
evt.GiveItem{1,1,1} 
```

**Comment by Rod-L** [comment]
3. events.lua:2137 hookfunction method hides ItemsTxt offset: beginning of 0x453ECC is:
```
	push ebp
	mov ebp, esp
	sub esp, 0xc94
```
0xc94 is amount of allowed lines in items.txt multiplied by 4. I'm modifying this value inside RemoveItemsLimits.lua. I've found no way to do it before hookfunction is called, thus i have to modify events.lua.

**Comment by GrayFace** [comment]
Use `mem.BatchAdd({0x453ECF+2}, New - Old)`, it will account for code relocation.
